#NumPy Basics

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
lis = [1, 2, 3, 4, 5, 5.5, 5+6j, True] #Heterogeneous data

In [ ]:
import numpy as np
l = [1, 2, 3, 4, 5]
np.array(l)

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array(l)
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr1.ndim

2

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.matrix([1, 2, 3, 4, 5])

matrix([[1, 2, 3, 4, 5]])

In [ ]:
mat = np.matrix([1, 2, 3, 4, 5])

In [ ]:
mat

matrix([[1, 2, 3, 4, 5]])

In [ ]:
mat.ndim

2

In [ ]:
type(mat)

numpy.matrix

In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [ ]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3.ndim

3

In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
#more ways to creat array

In [ ]:
l = [1, 2, 3]
arr = np.asarray(l)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
mat

matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [ ]:
#tuple to array
t = ([1, 2, 3], [4, 5, 6])
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#indexing

In [ ]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0]

1

In [ ]:
arr[0] = 1000

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
#shallow copy
a = arr

In [ ]:
a

array([1000,    2,    3,    4,    5])

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
a[0] = 1

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
#deep copy
a = arr.copy()

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
a[0] = 5000

In [ ]:
a

array([5000,    2,    3,    4,    5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
#multiple approaches to generate an array

In [ ]:
np.fromfunction(lambda i, j : i == j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr = np.fromfunction(lambda i : i**2, (6, ))

In [ ]:
arr

array([ 0.,  1.,  4.,  9., 16., 25.])

In [ ]:
arr1 = np.fromfunction(lambda i, j : i == j, (3, 3))

In [ ]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr1.ndim

2

In [ ]:
arr1.shape

(3, 3)

In [ ]:
arr1.size

9

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [ ]:
iterable = (i for i in range(5))

In [ ]:
iterable

<generator object <genexpr> at 0x7f400b867850>

In [ ]:
#we can also make an numpy array with iterable

In [ ]:
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring('22 23 24', sep = " ")

array([22., 23., 24.])

In [ ]:
np.fromstring('23 24 25', sep = " ", dtype = int)

array([23, 24, 25])

In [ ]:
string = "Ajay, Bijay, Sanjay"

In [ ]:
string.split(", ")

['Ajay', 'Bijay', 'Sanjay']

In [ ]:
np.array(string.split(", "))

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [ ]:
range(0, 10)

range(0, 10)

In [ ]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#NumPy Advance-1

In [ ]:
import numpy as np

In [ ]:
a = np.zeros(5)

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(5,)

In [ ]:
a.size

5

In [ ]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((3, 4))

In [ ]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
b = np.ones(5, dtype = int)

In [ ]:
b

array([1, 1, 1, 1, 1])

In [ ]:
b.ndim

1

In [ ]:
b.shape

(5,)

In [ ]:
b.size

5

In [ ]:
b = np.ones((5, 6))

In [ ]:
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(5, 6)

In [ ]:
b.size

30

In [ ]:
np.array([[1, 2, 4], [6, 7, 8]])

array([[1, 2, 4],
       [6, 7, 8]])

In [ ]:
np.zeros((7, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#3-d array

In [ ]:
np.zeros(1)

array([0.])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((1, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr = np.zeros((1, 4, 6))

In [ ]:
arr.shape

(1, 4, 6)

In [ ]:
arr.size

24

In [ ]:
arr.ndim

3

In [ ]:
arr = np.zeros((1, 2, 3, 4, 5))

In [ ]:
arr.ndim

5

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = arr+5

In [ ]:
a*2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [ ]:
a-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.empty((3, 4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.empty((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
import random
random.choice((1, 2, 3, 4, 5))

4

In [ ]:
random.choice("Ajay")

'y'

In [ ]:
random.choice("Shayan")

'n'

In [ ]:
random.randrange(1, 20)

11

In [ ]:
random.randrange(1, 50)

24

In [ ]:
random.random()

0.8646441947535666

In [ ]:
random.random()

0.06076952171679906

In [ ]:
lis = [1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)

In [ ]:
lis

[4, 5, 3, 1, 2]

In [ ]:
random.uniform(7, 14)

11.516631964704189

In [ ]:
random.uniform(7, 14)

8.53837346537311

In [ ]:
random.uniform(7, 14)

11.274715875102846

In [ ]:
random.uniform(7, 14)

12.448679924473362

In [ ]:
#random number related concept in array

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample()

0.025959421990511933

In [ ]:
np.random.random_sample((5, ))

array([0.9360483 , 0.14540152, 0.94163613, 0.38737886, 0.65299526])

In [ ]:
np.random.random_sample((7, ))

array([0.50473753, 0.3945956 , 0.4374294 , 0.55506873, 0.35581839,
       0.93482748, 0.26979476])

In [ ]:
np.random.random_sample((3, 4))

array([[0.29488334, 0.46344893, 0.91592876, 0.65573192],
       [0.74532572, 0.81546642, 0.81782678, 0.17303339],
       [0.54313652, 0.53178142, 0.90895371, 0.84617235]])

In [ ]:
np.random.rand(1)

array([0.52862659])

In [ ]:
np.random.rand(2)

array([0.75317625, 0.62425857])

In [ ]:
np.random.rand(5)

array([0.50714267, 0.56579312, 0.36172544, 0.94377583, 0.26159803])

In [ ]:
np.random.randn(2, 3)

array([[-1.63076188, -1.03365991, -0.01009937],
       [ 0.89822548, -1.77572966,  0.11719108]])

In [ ]:
np.random.randn(5, 6)

array([[ 0.23699991,  0.70180791,  0.50006063,  0.4904491 ,  1.12329555,
        -0.82154926],
       [-0.52735013, -0.43158366,  1.33980493,  0.10876503,  0.86868924,
        -0.54815814],
       [ 1.1733642 , -0.23814111,  2.35520538, -1.10928523,  1.32443942,
        -1.05783969],
       [ 0.06309318,  0.74788812,  1.14440056,  2.55603463,  0.1156936 ,
         0.05131938],
       [ 1.3212457 , -0.4946013 , -1.70738783, -0.12823183, -1.53224818,
        -0.37091772]])

In [ ]:
np.random.randint(1, 5)

1

In [ ]:
np.random.randint(1, 10)

7

In [ ]:
np.random.randint(1, 5, size = (3, 4))

array([[4, 2, 4, 1],
       [2, 3, 2, 1],
       [1, 2, 4, 4]])

In [ ]:
arr = np.random.randint(1, 5, (4, 5))

In [ ]:
arr

array([[4, 4, 4, 1, 2],
       [2, 2, 3, 1, 1],
       [2, 3, 4, 1, 1],
       [3, 1, 3, 1, 3]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(4, 5)

In [ ]:
arr.size

20

In [ ]:
#reshape the array

In [ ]:
arr

array([[4, 4, 4, 1, 2],
       [2, 2, 3, 1, 1],
       [2, 3, 4, 1, 1],
       [3, 1, 3, 1, 3]])

In [ ]:
arr.shape

(4, 5)

In [ ]:
arr.reshape(2, 10)

array([[4, 4, 4, 1, 2, 2, 2, 3, 1, 1],
       [2, 3, 4, 1, 1, 3, 1, 3, 1, 3]])

In [ ]:
arr.reshape(5, 4)

array([[4, 4, 4, 1],
       [2, 2, 2, 3],
       [1, 1, 2, 3],
       [4, 1, 1, 3],
       [1, 3, 1, 3]])

In [ ]:
arr = np.random.randint(1, 5, (3, 4))

In [ ]:
arr

array([[1, 4, 4, 4],
       [3, 1, 4, 1],
       [1, 2, 2, 2]])

In [ ]:
arr.reshape(2,6)

array([[1, 4, 4, 4, 3, 1],
       [4, 1, 1, 2, 2, 2]])

In [ ]:
arr

array([[1, 4, 4, 4],
       [3, 1, 4, 1],
       [1, 2, 2, 2]])

In [ ]:
arr.reshape(4, -1)

array([[1, 4, 4],
       [4, 3, 1],
       [4, 1, 1],
       [2, 2, 2]])

In [ ]:
arr.reshape(-1, 4)

array([[1, 4, 4, 4],
       [3, 1, 4, 1],
       [1, 2, 2, 2]])

In [ ]:
arr.reshape(12, 1).base

array([[1, 4, 4, 4],
       [3, 1, 4, 1],
       [1, 2, 2, 2]])

In [ ]:
arr.reshape(2, 2, 3)

array([[[1, 4, 4],
        [4, 3, 1]],

       [[4, 1, 1],
        [2, 2, 2]]])

In [ ]:
arr.reshape(1, 2, 2, 3)

array([[[[1, 4, 4],
         [4, 3, 1]],

        [[4, 1, 1],
         [2, 2, 2]]]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.reshape(4, 3, 1)

array([[[1],
        [4],
        [4]],

       [[4],
        [3],
        [1]],

       [[4],
        [1],
        [1]],

       [[2],
        [2],
        [2]]])

In [ ]:
#conditions on array

In [ ]:
arr = np.random.randint(1, 10, (5, 6))

In [ ]:
arr

array([[5, 3, 7, 7, 5, 3],
       [8, 9, 1, 3, 3, 3],
       [5, 3, 6, 3, 2, 2],
       [9, 3, 9, 3, 3, 4],
       [8, 9, 1, 6, 1, 3]])

In [ ]:
arr.shape

(5, 6)

In [ ]:
arr.size

30

In [ ]:
arr.ndim

2

In [ ]:
arr > 3

array([[ True, False,  True,  True,  True, False],
       [ True,  True, False, False, False, False],
       [ True, False,  True, False, False, False],
       [ True, False,  True, False, False,  True],
       [ True,  True, False,  True, False, False]])

In [ ]:
arr[arr > 3]

array([5, 7, 7, 5, 8, 9, 5, 6, 9, 9, 4, 8, 9, 6])

In [ ]:
arr < 3

array([[False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False,  True, False,  True, False]])

In [ ]:
arr[arr < 3]

array([1, 2, 2, 1, 1])

In [ ]:
#access elements in an array

In [ ]:
arr

array([[5, 3, 7, 7, 5, 3],
       [8, 9, 1, 3, 3, 3],
       [5, 3, 6, 3, 2, 2],
       [9, 3, 9, 3, 3, 4],
       [8, 9, 1, 6, 1, 3]])

In [ ]:
arr[0]

array([5, 3, 7, 7, 5, 3])

In [ ]:
arr[1]

array([8, 9, 1, 3, 3, 3])

In [ ]:
arr[2]

array([5, 3, 6, 3, 2, 2])

In [ ]:
arr[3]

array([9, 3, 9, 3, 3, 4])

In [ ]:
arr[4]

array([8, 9, 1, 6, 1, 3])

In [ ]:
arr[0, 0]

5

In [ ]:
arr[0, 1]

3

In [ ]:
arr[0:3]

array([[5, 3, 7, 7, 5, 3],
       [8, 9, 1, 3, 3, 3],
       [5, 3, 6, 3, 2, 2]])

In [ ]:
arr[0:3, [0, 2]]

array([[5, 7],
       [8, 1],
       [5, 6]])

In [ ]:
arr[0:3, [0, 5]]

array([[5, 3],
       [8, 3],
       [5, 2]])

In [ ]:
#slicing on both rows and columns together

In [ ]:
arr

array([[5, 3, 7, 7, 5, 3],
       [8, 9, 1, 3, 3, 3],
       [5, 3, 6, 3, 2, 2],
       [9, 3, 9, 3, 3, 4],
       [8, 9, 1, 6, 1, 3]])

In [ ]:
arr[0:3, 1:4]

array([[3, 7, 7],
       [9, 1, 3],
       [3, 6, 3]])

In [ ]:
#mathematical operations on two arrays

In [ ]:
arr1 = np.random.randint(1, 2, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [ ]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [ ]:
arr1+arr2

array([[2, 2, 2],
       [2, 3, 3],
       [2, 2, 2]])

In [ ]:
arr1-arr2

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [ 0,  0,  0]])

In [ ]:
arr1*arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [ ]:
arr1, arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 2, 2],
        [1, 1, 1]]))

In [ ]:
arr1/arr2

array([[1. , 1. , 1. ],
       [1. , 0.5, 0.5],
       [1. , 1. , 1. ]])

In [ ]:
arr1/0

<ipython-input-231-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#matrix multiplication

In [ ]:
arr1 @ arr2

array([[3, 4, 4],
       [3, 4, 4],
       [3, 4, 4]])

In [ ]:
#or
np.dot(arr1, arr2)

array([[3, 4, 4],
       [3, 4, 4],
       [3, 4, 4]])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
import numpy as np
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.array([1, 2, 3, 4, 5])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np

arr = np.zeros((3, 4))

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
#Transpose

In [ ]:
a = np.array([[1, 2, 3, 4, 5]])

In [ ]:
a

array([[1, 2, 3, 4, 5]])

In [ ]:
a.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

#NumPy Advance-2

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [ ]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [ ]:
arr2

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [ ]:
arr1.flatten()

array([1, 1, 1, 2, 2, 2, 1, 2, 2])

In [ ]:
arr2.flatten()

array([1, 2, 1, 1, 1, 2, 2, 1, 2])

In [ ]:
arr3 = np.random.randint(1, 5, (5, 5))

In [ ]:
arr3

array([[4, 4, 2, 2, 2],
       [1, 3, 2, 2, 2],
       [4, 2, 2, 3, 4],
       [3, 4, 4, 2, 1],
       [3, 4, 1, 4, 3]])

In [ ]:
arr3.flatten()

array([4, 4, 2, 2, 2, 1, 3, 2, 2, 2, 4, 2, 2, 3, 4, 3, 4, 4, 2, 1, 3, 4,
       1, 4, 3])

In [ ]:
#expand dimension

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
np.expand_dims(arr, axis = 0)

array([[1, 2, 3, 4, 5]])

In [ ]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
np.expand_dims(arr, axis = 1).ndim

2

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [ ]:
a = np.array([[1], [2], [3]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
a.ndim

2

In [ ]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.expand_dims(arr, axis = 0).ndim

3

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
#convert 2-d into 1-d

In [ ]:
np.squeeze(a)

array([1, 2, 3])

In [ ]:
arr2 = np.array([[1], [4], [7]])

In [ ]:
arr2

array([[1],
       [4],
       [7]])

In [ ]:
np.squeeze(arr2)

array([1, 4, 7])

In [ ]:
#repeat

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [ ]:
np.repeat(arr1, 2)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2])

In [ ]:
np.repeat(arr1, 2, axis = 0)

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [1, 2, 2],
       [1, 2, 2]])

In [ ]:
arr2

array([[1],
       [4],
       [7]])

In [ ]:
np.repeat(arr2, 2)

array([1, 1, 4, 4, 7, 7])

In [ ]:
np.repeat(arr2, 2, axis = 0)

array([[1],
       [1],
       [4],
       [4],
       [7],
       [7]])

In [ ]:
np.repeat(arr2, 5, axis = 1)

array([[1, 1, 1, 1, 1],
       [4, 4, 4, 4, 4],
       [7, 7, 7, 7, 7]])

In [ ]:
a

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [ ]:
c = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
c.ndim

2

In [ ]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [ ]:
np.roll(c, -3)

array([[4, 5],
       [6, 7],
       [8, 1],
       [2, 3]])

In [ ]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.roll(c, 5)

array([[4, 5],
       [6, 7],
       [8, 1],
       [2, 3]])

In [ ]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.roll(c, 2, axis = 0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [ ]:
np.roll(c, 1, axis = 1)

array([[2, 1],
       [4, 3],
       [6, 5],
       [8, 7]])

In [ ]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [ ]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [ ]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr1 + arr2

array([[2, 4, 3],
       [3, 3, 2],
       [4, 2, 3]])

In [ ]:
arr1 - arr2

array([[ 0,  0,  1],
       [-1, -1,  0],
       [ 0,  0, -1]])

In [ ]:
arr1 * arr2

array([[1, 4, 2],
       [2, 2, 1],
       [4, 1, 2]])

In [ ]:
arr1 / arr2

array([[1. , 1. , 2. ],
       [0.5, 0.5, 1. ],
       [1. , 1. , 0.5]])

In [ ]:
arr1 > arr2

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
arr1 < arr2

array([[False, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [ ]:
arr1 == arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
~arr1

array([[-2, -3, -2],
       [-3, -3, -2],
       [-3, -2, -3]])

In [ ]:
#operations on numpy string array

In [ ]:
d = np.array(["pw", "skills"])

In [ ]:
d

array(['pw', 'skills'], dtype='<U6')

In [ ]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [ ]:
np.char.lower(d)

array(['pw', 'skills'], dtype='<U6')

In [ ]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
#Mathematical Functions

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743]])

In [ ]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684]])

In [ ]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986]])

In [ ]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [ ]:
np.power(arr1, 3)

array([[1, 8, 1],
       [8, 8, 1],
       [8, 1, 8]])

In [ ]:
np.max(arr1)

2

In [ ]:
np.min(arr1)

1

In [ ]:
np.mean(arr1)

1.5555555555555556

In [ ]:
np.std(arr1)

0.4969039949999533

In [ ]:
np.var(arr1)

0.2469135802469136

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.multiply(arr1, arr2)

array([[1, 4, 1],
       [4, 4, 1],
       [4, 1, 4]])

In [ ]:
arr1 * arr2

array([[1, 4, 1],
       [4, 4, 1],
       [4, 1, 4]])

In [ ]:
np.add(arr1, arr2)

array([[2, 4, 2],
       [4, 4, 2],
       [4, 2, 4]])

In [ ]:
arr1 + arr2

array([[2, 4, 2],
       [4, 4, 2],
       [4, 2, 4]])

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
np.mod(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1 % arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [ ]:
#Sorting and Searching in numpy

In [ ]:
e = np.array([5, 6, 1, 2])

In [ ]:
e

array([5, 6, 1, 2])

In [ ]:
np.sort(e)

array([1, 2, 5, 6])

In [ ]:
f = np.array([5, 199, 200, 6, 7, 8])

In [ ]:
f

array([  5, 199, 200,   6,   7,   8])

In [ ]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [ ]:
np.searchsorted(f, 170)

6

In [ ]:
np.count_nonzero(f)

6

In [ ]:
f

array([  5, 199, 200,   6,   7,   8])

In [ ]:
f > 0

array([ True,  True,  True,  True,  True,  True])

In [ ]:
f[f > 0]

array([  5, 199, 200,   6,   7,   8])

In [ ]:
np.where(f > 0)

(array([0, 1, 2, 3, 4, 5]),)

In [ ]:
np.extract(f > 0, f)

array([  5, 199, 200,   6,   7,   8])

In [ ]:
f

array([  5, 199, 200,   6,   7,   8])

In [ ]:
f.byteswap()

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,   576460752303423488])

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#numpy linear algebra function

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr1 @ arr2

array([[7, 7, 5],
       [8, 9, 6],
       [8, 8, 7]])

In [ ]:
#Determinant

In [ ]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
np.linalg.det(arr1)

-2.9999999999999996

In [ ]:
# in matrix you cannot divide by another matrix

In [ ]:
#inverse

In [ ]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
np.linalg.inv(arr2)

array([[-1.        ,  1.        ,  0.        ],
       [ 0.66666667,  0.        , -0.33333333],
       [ 0.66666667, -1.        ,  0.66666667]])

In [ ]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [ ]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [ ]:
b = np.array([16, 8, 0])

In [ ]:
np.linalg.solve(a, b)

array([2.59630607, 0.84432718, 2.21635884])