In [1]:
import numpy as np

In [3]:
l1 = [1, 2, 3]
l2 = [10, 20, 30]

In [4]:
print(type(l1))
print(type(l2))

<class 'list'>
<class 'list'>


In [5]:
l1 + l2

[1, 2, 3, 10, 20, 30]

In [6]:
#But I want mathematical calculation

In [ ]:
l1 - l2 #Error

In [8]:
l1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
# list is not made for mathematical operations

In [10]:
# convert list to tuple
tuple(l1)

(1, 2, 3)

In [16]:
# convert list as array
a1 = np.array(l1)

In [17]:
a2 = np.array(l2)

In [18]:
type(a1)

numpy.ndarray

In [19]:
type(a2)

numpy.ndarray

In [20]:
print(a1)

[1 2 3]


In [21]:
print(a2)

[10 20 30]


In [22]:
a1

array([1, 2, 3])

In [23]:
a2

array([10, 20, 30])

In [24]:
a = a1 + a2

In [25]:
a

array([11, 22, 33])

In [26]:
sub = a1 - a2

In [27]:
sub

array([ -9, -18, -27])

In [28]:
mul = a1 * a2

In [29]:
mul

array([10, 40, 90])

In [30]:
a1 = np.array([10, 20])
a2 = np.array([1, 2, 3])

In [ ]:
# the number of elements both the array should be same
a1 + a2 # Error

In [32]:
a1 = np.array([10, 20])
a2 = np.array([1, 2])

In [33]:
print(a1+a2)

[11 22]


In [35]:
print(a1 - a1)
print(a1 * a2)
print(a1 // a2)

[0 0]
[10 40]
[10 10]


In [36]:
type(a1)

numpy.ndarray

In [37]:
a1.dtype

dtype('int64')

In [38]:
a2.dtype

dtype('int64')

In [39]:
a1 = [2, 3, 45, 2, 3, 4, 5]

In [40]:
a1[0]

2

In [41]:
a1[4]

3

In [42]:
a1[2:5]

[45, 2, 3]

In [43]:
a1[2:6]

[45, 2, 3, 4]

In [44]:
np.mean(a1)

9.142857142857142

In [45]:
np.min(a1)

2

In [46]:
np.max(a1)

45

In [47]:
np.argmin(a1)

0

In [48]:
np.argmax(a1)

2

In [49]:
a1

[2, 3, 45, 2, 3, 4, 5]

In [50]:
a2

array([1, 2])

In [51]:
np.argmin(a2)

0

In [52]:
np.argmax(a2)

1

In [53]:
a1

[2, 3, 45, 2, 3, 4, 5]

In [55]:
a1 = np.array(a1)

In [56]:
a1

array([ 2,  3, 45,  2,  3,  4,  5])

In [57]:
a1 > 5

array([False, False,  True, False, False, False, False])

In [58]:
a1[a1 > 5]

array([45])

In [59]:
a1.ndim

1

In [60]:
a1.shape

(7,)

In [61]:
a1.size

7

In [62]:
l1 = [[1, 2, 3], [4, 5, 6]]

In [63]:
l1 = np.array(l1)

In [64]:
l1

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
type(l1)

numpy.ndarray

In [66]:
l1.ndim

2

In [67]:
l1.shape

(2, 3)

In [68]:
l1.size

6

In [69]:
l1.dtype

dtype('int64')

In [70]:
print(l1.ndim)
print(l1.shape)
print(l1.size)
print(l1.dtype)

2
(2, 3)
6
int64


In [72]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
zeros = np.zeros((3, 4), dtype = int)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [74]:
a2 = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]])

In [75]:
a2[1, 0]

10

In [77]:
a2[1, 2]

30

In [78]:
a2

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [79]:
a2.shape

(3, 4)

In [80]:
a2.reshape(4, 3)

array([[  1,   2,   3],
       [  4,  10,  20],
       [ 30,  40, 100],
       [200, 300, 400]])

In [81]:
a2.reshape(6, 2)

array([[  1,   2],
       [  3,   4],
       [ 10,  20],
       [ 30,  40],
       [100, 200],
       [300, 400]])

In [82]:
a1 = np.array([10, 20])
a2 = np.array([1, 2])

In [84]:
a3 = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
a3

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [85]:
a3.ndim

3

In [86]:
a3.shape

(1, 4, 2)

In [87]:
a3.size

8

In [88]:
a3.dtype

dtype('int64')

In [89]:
type(a3)

numpy.ndarray